from pathlib import Path


WIDTH = 224
HEIGHT = 256
WINDOW_SCALE = 3
WINDOW_WIDTH = WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = HEIGHT * WINDOW_SCALE
TITLE = "Bubble Dungeon - Prototype"
FPS = 60

BACKGROUND_COLOR = (25, 28, 40)
PLATFORM_COLOR = (70, 120, 80)
PLAYER_COLOR = (240, 190, 90)
ENEMY_COLOR = (210, 95, 100)
ENEMY_TRAPPED_COLOR = (120, 210, 255)
BUBBLE_COLOR = (150, 220, 255)
HUD_COLOR = (245, 245, 245)

GROUND_HEIGHT = 10
GROUND_Y = HEIGHT - GROUND_HEIGHT

PLAYER_WIDTH = 14
PLAYER_HEIGHT = 16
PLAYER_SPEED = 86
PLAYER_JUMP_VELOCITY = -285
PLAYER_JUMP_BUFFER_DURATION = 0.12
PLAYER_COYOTE_TIME = 0.08
PLAYER_ATTACK_ANIMATION_DURATION = 0.34

ENEMY_WIDTH = 16
ENEMY_HEIGHT = 16
ENEMY_SPEED = 42
ENEMY_DEATH_ANIMATION_DURATION = 0.7
ENEMY_DEATH_FRAME_DURATION = 0.09
ENEMY_DEATH_BOUNCE_VELOCITY = -170
ENEMY_DEATH_GRAVITY = 260
ENEMY_DEATH_HORIZONTAL_VELOCITY = 82

BUBBLE_START_RADIUS = 5
BUBBLE_RADIUS = 10
BUBBLE_SPEED = 280
BUBBLE_BRAKE_DURATION = 0.34
BUBBLE_RISE_SPEED = 34
BUBBLE_CAPTURE_MIN_HORIZONTAL_SPEED = 70
BUBBLE_POP_IMPACT_SPEED = 190
BUBBLE_CHAIN_POP_MARGIN = 8
BUBBLE_REPEL_STRENGTH = 0.35
BUBBLE_LIFETIME = 18
PLAYER_BUBBLE_POP_MIN_UPWARD_SPEED = 35
TRAP_DURATION = 18
POP_EFFECT_DURATION = 0.4
COLLECTABLE_LIFETIME = 8.0
COLLECTABLE_SIZE = 14
COLLECTABLE_GRAVITY = 650
COLLECTABLE_BOUNCE_VELOCITY = -210
COLLECTABLE_HORIZONTAL_VELOCITY = 70
COLLECTABLE_PICKUP_DELAY = 0.9

GRAVITY = 720
STARTING_LIVES = 3
SPAWN_INVULNERABILITY_DURATION = 1.25
READY_DURATION = 1.8
LEVEL_END_DELAY = 2.5
LEVEL_TRANSITION_DURATION = 1.35
PLAYER_DEATH_DURATION = 2.0

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LEVELS_DIR = PROJECT_ROOT / "levels"
ASSETS_DIR = PROJECT_ROOT / "assets"
