from pathlib import Path


BASE_WIDTH = 224
BASE_HEIGHT = 256
NATIVE_RESOLUTION_SCALE = 3


def scale_px(value: int | float) -> int:
    return round(value * NATIVE_RESOLUTION_SCALE)


WIDTH = scale_px(BASE_WIDTH)
HEIGHT = scale_px(BASE_HEIGHT)
WINDOW_SCALE = 1
WINDOW_WIDTH = WIDTH * WINDOW_SCALE
WINDOW_HEIGHT = HEIGHT * WINDOW_SCALE
TITLE = "Bubble Dungeon - Prototype"
FPS = 60

BACKGROUND_COLOR = (25, 28, 40)
PLATFORM_COLOR = (70, 120, 80)
PLAYER_COLOR = (240, 190, 90)
ENEMY_COLOR = (210, 95, 100)
ENEMY_TRAPPED_COLOR = (120, 210, 255)
BUBBLE_COLOR = (150, 220, 255)
HUD_COLOR = (245, 245, 245)

GROUND_HEIGHT = scale_px(10)
GROUND_Y = HEIGHT - GROUND_HEIGHT

PLAYER_WIDTH = scale_px(14)
PLAYER_HEIGHT = scale_px(16)
PLAYER_SPEED = scale_px(86)
PLAYER_JUMP_VELOCITY = -scale_px(285)
PLAYER_JUMP_BUFFER_DURATION = 0.12
PLAYER_COYOTE_TIME = 0.08
PLAYER_ATTACK_ANIMATION_DURATION = 0.34

ENEMY_WIDTH = scale_px(16)
ENEMY_HEIGHT = scale_px(16)
ENEMY_SPEED = scale_px(42)
ENEMY_DEATH_ANIMATION_DURATION = 0.7
ENEMY_DEATH_FRAME_DURATION = 0.09
ENEMY_DEATH_BOUNCE_VELOCITY = -scale_px(170)
ENEMY_DEATH_GRAVITY = scale_px(260)
ENEMY_DEATH_HORIZONTAL_VELOCITY = scale_px(82)

BUBBLE_START_RADIUS = scale_px(5)
BUBBLE_RADIUS = scale_px(10)
BUBBLE_SPEED = scale_px(280)
BUBBLE_BRAKE_DURATION = 0.34
BUBBLE_RISE_SPEED = scale_px(34)
BUBBLE_CAPTURE_MIN_HORIZONTAL_SPEED = scale_px(70)
BUBBLE_POP_IMPACT_SPEED = scale_px(190)
BUBBLE_CHAIN_POP_MARGIN = scale_px(8)
BUBBLE_REPEL_STRENGTH = 0.35
BUBBLE_LIFETIME = 18
PLAYER_BUBBLE_POP_MIN_UPWARD_SPEED = scale_px(35)
TRAP_DURATION = 18
POP_EFFECT_DURATION = 0.4
COLLECTABLE_LIFETIME = 8.0
COLLECTABLE_SIZE = scale_px(14)
COLLECTABLE_GRAVITY = scale_px(650)
COLLECTABLE_BOUNCE_VELOCITY = -scale_px(210)
COLLECTABLE_HORIZONTAL_VELOCITY = scale_px(70)
COLLECTABLE_PICKUP_DELAY = 0.9

GRAVITY = scale_px(720)
STARTING_LIVES = 3
SPAWN_INVULNERABILITY_DURATION = 1.25
READY_DURATION = 1.8
LEVEL_END_DELAY = 2.5
LEVEL_TRANSITION_DURATION = 1.35
PLAYER_DEATH_DURATION = 2.0

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LEVELS_DIR = PROJECT_ROOT / "levels"
ASSETS_DIR = PROJECT_ROOT / "assets"
